services:
  server:
    build: .
    # uncomment below for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 'all'
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/v2/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 6s
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"